name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4
      # {言語セットアップ}
      # {依存インストール}
      # {Lint}
      # {テスト}

  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4
      # {言語セットアップ}
      # {依存インストール}
      # {Lint}
      # {ビルド}
